<?php

namespace Samane\Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employeur extends \Employeur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Employeur' . "\0" . 'id', '' . "\0" . 'Employeur' . "\0" . 'numIdentification', '' . "\0" . 'Employeur' . "\0" . 'raisonSocial', '' . "\0" . 'Employeur' . "\0" . 'nom_employeur', '' . "\0" . 'Employeur' . "\0" . 'adresse_employeur', '' . "\0" . 'Employeur' . "\0" . 'clients'];
        }

        return ['__isInitialized__', '' . "\0" . 'Employeur' . "\0" . 'id', '' . "\0" . 'Employeur' . "\0" . 'numIdentification', '' . "\0" . 'Employeur' . "\0" . 'raisonSocial', '' . "\0" . 'Employeur' . "\0" . 'nom_employeur', '' . "\0" . 'Employeur' . "\0" . 'adresse_employeur', '' . "\0" . 'Employeur' . "\0" . 'clients'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employeur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumIdentification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumIdentification', []);

        return parent::getNumIdentification();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumIdentification($numIdentification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumIdentification', [$numIdentification]);

        return parent::setNumIdentification($numIdentification);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSocial', []);

        return parent::getRaisonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSocial($raisonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSocial', [$raisonSocial]);

        return parent::setRaisonSocial($raisonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom_employeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom_employeur', []);

        return parent::getNom_employeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom_employeur($nom_employeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom_employeur', [$nom_employeur]);

        return parent::setNom_employeur($nom_employeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse_employeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse_employeur', []);

        return parent::getAdresse_employeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse_employeur($adresse_employeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse_employeur', [$adresse_employeur]);

        return parent::setAdresse_employeur($adresse_employeur);
    }

}
